# Generated by Django 3.1.3 on 2024-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptoms', models.CharField(max_length=500)),
                ('Causes', models.CharField(max_length=500)),
                ('Disease', models.CharField(max_length=500)),
                ('Medicine', models.CharField(max_length=500)),
                ('Specialist', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialist', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='onlineuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alg_name', models.CharField(max_length=100)),
                ('sc1', models.FloatField()),
                ('sc2', models.FloatField()),
                ('sc3', models.FloatField()),
                ('sc4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_n', models.CharField(max_length=1000)),
                ('an_s', models.CharField(max_length=1000)),
            ],
        ),
    ]
