# Generated by Django 3.1.3 on 2024-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=159)),
                ('email', models.CharField(max_length=159)),
                ('pass_word', models.CharField(max_length=159)),
                ('phone', models.CharField(max_length=159)),
                ('city', models.CharField(max_length=159)),
                ('gender', models.CharField(max_length=159)),
                ('age', models.CharField(max_length=159)),
            ],
        ),
        migrations.DeleteModel(
            name='onlineuser',
        ),
    ]
