# Generated by Django 3.1.3 on 2024-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20240406_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
