# Generated by Django 3.1.3 on 2024-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240406_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='docchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('chatbw', models.CharField(max_length=100)),
                ('stz', models.CharField(max_length=10)),
            ],
        ),
    ]
