# Generated by Django 3.1.3 on 2024-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_docchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='stz',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
